#workflows
#should have name
name: Hello

#on tells when the workflow will run
on:
  workflow_dispatch:

#jobs
#should be inside workflows
#job tells what the workflow should do, there can be one or more jobs hence we write jobs
jobs:
#1st job (give indentation)
  say-hello:
  #create an ephermeral container using ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: say hello to everyone
        run: echo "Hello Dosto"

#steps
#should be inside job

#actions
#should be inside steps
